version: '3.9'
services:

  main:
    build: .
    depends_on:
      - postgres_db
    volumes:
      - ./:/usr/src/app:ro
    ports:
      - 8080:8080
    #env_file:
    #  - ./.ev
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5678
      - POSTGRES_DB=postgres_db

  postgres_db:
    image: postgres:latest
    container_name: database_db_container
    ports:
      - 5678:5678
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5678
      - POSTGRES_DB=postgres_db
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data


volumes:
  postgres_db_volume:
