version: '3.3'
services:

  gabriel_request_handler:
    build: request_handler/
    #image: icemikl/gabriel_request_handler:latest
    container_name: gabriel_request_handler_container
    depends_on:
      - postgres_db
      - adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres_db
      - BASIC_AUTH_USERNAME=user
      - BASIC_AUTH_PASSWORD=gabriel_user
      - BASIC_AUTH_FORCE=True


  gabriel_db_manager:
    build: db_manager/
    #image: icemikl/gabriel_db_manager:latest
    container_name: gabriel_db_manager_container
    depends_on:
      - postgres_db
      - adminer
    restart: always
    ports:
    - 8087:8087
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres_db
      - BASIC_AUTH_USERNAME=user
      - BASIC_AUTH_PASSWORD=gabriel_user
      - BASIC_AUTH_FORCE=True


  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db


  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8888:8080

